Repository BIH-CEI/ERKER2Phenopackets, pull requests merged in 2023-09, with the labels that each got.

#55 Update README.md to include installation details
  README.md
Labels: documentation

#101 92 store ref allele in vcf record
  ERKER2Phenopackets/data/config/config.cfg
  ERKER2Phenopackets/src/MC4R/MapMC4R.py
Labels: enhancement

#146 125 daniels comments
  ERKER2Phenopackets/data/config/config.cfg
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/0.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/1.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/10.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/11.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/12.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/13.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/14.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/15.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/16.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/17.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/18.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/19.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/2.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/20.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/21.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/22.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/23.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/24.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/25.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/26.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/27.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/28.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/29.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/3.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/30.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/31.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/32.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/33.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/34.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/35.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/36.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/37.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/38.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/39.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/4.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/40.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/41.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/42.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/43.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/44.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/45.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/46.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/47.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/48.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/49.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/5.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/6.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/7.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/8.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/9.json
  ERKER2Phenopackets/src/MC4R/MapMC4R.py
  ERKER2Phenopackets/src/MC4R/MappingDicts.py
Labels: bug, enhancement

#161 153 update erker v17 to fix zygosity
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/0.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/1.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/10.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/11.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/12.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/13.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/14.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/15.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/16.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/17.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/18.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/19.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/2.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/20.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/21.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/22.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/23.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/24.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/25.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/26.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/27.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/28.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/29.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/3.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/30.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/31.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/32.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/33.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/34.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/35.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/36.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/37.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/38.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/39.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/4.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/40.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/41.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/42.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/43.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/44.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/45.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/46.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/47.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/48.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/49.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/5.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/6.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/7.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/8.json
  ERKER2Phenopackets/data/out/phenopackets/example-phenopackets-from-synthetic-data/9.json
  ERKER2Phenopackets/data/sdv_synthetic_data.csv
  ERKER2Phenopackets/src/MC4R/MapMC4R.py
  ERKER2Phenopackets/src/MC4R/Pipeline.py
  ERKER2Phenopackets/src/utils/ParallelizationUtils.py
Labels: bug, enhancement
